---
title: '`r paste("Experiment", params$experiment)`'
author:
  - name: Matti Vuorre 
    affiliation: Columbia University
date: "`r Sys.Date()`"
output: 
  radix::radix_article:
    toc: true
    toc_depth: 2
    self_contained: false
params:
  experiment: 1
---

```{r setup, include=FALSE}
source("functions.R")
library(knitr)
library(ggbeeswarm)
library(tidyverse)
library(summarytools)
library(broom)
library(scales)
library(patchwork)
opts_chunk$set(
  echo = FALSE,
  error = TRUE,
  eval = TRUE,
  dev = c("png", "pdf"),
  fig.ext = c("png", "pdf"),
  fig.retina = 2
)
theme_set(theme_linedraw() + theme(panel.grid = element_blank()))
```

## Descriptives

```{r create-data}
dat <- read_csv("data/merged.csv", guess_max = 25000)

# Get data for this experiment only
dat <- filter(dat, exp == params$experiment)

# Drop factor levels of subject used in other experiments
dat$subject <- fct_drop(dat$subject)
```

```{r metrics-summarise}
dat_metrics <- dat %>%
  nest(-subject) %>%
  mutate(res = map(data, metrics, ordinal = FALSE)) %>%
  unnest(res, .drop = TRUE)

descr(
  select(dat_metrics, n, p, gz, da, gamma), 
  stats = c("mean", "sd", "min", "max", "q1", "q3", "n.valid"),
  transpose = TRUE
) %>% 
  kable(digits = 2)
```

## Resolution

### Gamma

```{r gamma-overall}
dat_metrics %>%
  summarise(
    N = n(),
    mean = mean(gz, na.rm = T),
    se = sd(gz, na.rm = T) / sqrt(N)
  ) %>% 
  kable(digits=3)
```

```{r gamma-subject-ttest}
t.test(dat_metrics$gz)
```

### da

```{r da-ttest}
t.test(dat_metrics$da)
```

## Resolution - performance correlation

```{r gamma-performance-plot, fig.cap = "Correlation between math performance and resolution."}
p_gamma_p <- dat_metrics %>%
  ggplot(aes(p, gz)) +
  geom_vline(xintercept = .25, col = NA) + # Ensure limits
  geom_vline(xintercept = 1, col = NA) + # Ensure limits
  geom_hline(yintercept = 0, lty = 2, size = .33) +
  geom_point(shape = 21, fill = "white", alpha = .75) +
  geom_smooth(method = lm, col = "black", size = .75, alpha = .33) +
  scale_x_continuous(
    breaks = c(.25, .5, .75, 1), 
    limits = c(.25, 1)
  ) +
  labs(
    x = "Proportion correct",
    y = "Gamma"
  )
```

Correlations between resolution and performance

```{r correlation-tests}
a <- dat_metrics %>% 
  select(subject, gz, da, p) %>% 
  gather(Metric, value, gz, da) %>% 
  group_by(Metric) %>% 
  nest() %>% 
  mutate(model = map(data, ~cor.test(.$value, .$p, method = "pearson"))) %>% 
  mutate(out = map(model, ~tidy(.))) %>% 
  unnest(out, .drop = TRUE) %>% 
  mutate(p.value = pvalue(p.value)) %>% 
  select(-alternative)

b <- dat_metrics %>% 
  select(subject, gamma, p) %>% 
  gather(Metric, value, gamma) %>% 
  group_by(Metric) %>% 
  nest() %>% 
  mutate(model = map(data, ~cor.test(.$value, .$p, method = "kendall"))) %>% 
  mutate(out = map(model, ~tidy(.))) %>% 
  unnest(out, .drop = TRUE) %>% 
  mutate(p.value = pvalue(p.value)) %>% 
  select(-alternative)

bind_rows(a, b) %>% 
  kable(digits = 2)
```

## Figure

```{r figure, fig.height = 3.4, fig.width = 6.6}
brinley(dat_metrics, p, gz) |
  brinley(dat_metrics, p, da) + 
  labs(y=expression(italic("d")[a]))
```

